### ISSUE TITLE
One click is saved as two.

### ISSUE THREAD

**Issue by Fomchenkov** [MarinX/keylogger#1]
Hello! I made a keylogger based on your library, but for some reason, one press of a button is saved as two. For the most part, I press A, and AA saves. What could be the problem?
Here is my code.
```
package main

import (
	"fmt"
	"os"

	"github.com/MarinX/keylogger"
)

const (
	// File for logging.
	filename = "/home/slava/file.log"
)

// Append string to file.
func appendIntoFile(filename, content string) {
	// Chech file exists.
	if _, err := os.Stat(filename); os.IsNotExist(err) {
		// Create file for loggin.
		f, err := os.Create(filename)
		if err != nil {
			panic(err)
		}
		defer f.Close()
	}

	file, err := os.OpenFile(filename, os.O_RDWR|os.O_APPEND, 0755)

	if err != nil {
		panic(err)
	}

	if _, err := file.WriteString(content); err != nil {
		panic(err)
	}

	defer file.Close()
}

func main() {
	devs, err := keylogger.NewDevices()

	if err != nil {
		fmt.Println(err)
		return
	}

	for _, val := range devs {
		fmt.Println("Id->", val.Id, "Device->", val.Name)
	}

	// Keyboard device.
	rd := keylogger.NewKeyLogger(devs[4])

	in, err := rd.Read()
	if err != nil {
		fmt.Println("Error!", err)
		return
	}

	for i := range in {
		if i.Type == keylogger.EV_KEY {
			fmt.Println(i.KeyString() + "\n")
			appendIntoFile(filename, i.KeyString()+"\n")
		}
	}
}
```

**Comment by MarinX** [comment]
Hi, thanks for the bug report.
Will try to replicate the issue.

Can you tell me which go version are you using ?

**Comment by Fomchenkov** [comment]
I using go1.8.

**Comment by MarinX** [comment]
I can confirm bug with older versions of go.
Seems like a double read, but I'm not sure.
Tested with mutex lock but same.

Will need to investigate more.
In the meantime, you can do a quick hack and add time.Sleep after reading a key

**Comment by FM1337** [comment]
Any updates on this?

**Comment by MarinX** [comment]
Hey @FM1337 ,
Yes!

After I found some free time to manage to look at my old library, I managed to do a complete rewrite with documentation, tests and better code handling.
Now it works as expected

I will release as soon as I finish the new README doc

**Comment by FM1337** [comment]
I can't wait to see it! Any chance that it could work on windows and linux or will it only just remain to work on linux?

**Comment by MarinX** [comment]
Updated :) 
You can checkout the example in example/main.go.

It's only linux based to showcase the reading/parsing from file without doing syscall.
I do not have plans for windows, yet.
