### ISSUE TITLE
[BUG] Indefinite loop on disconnect

### ISSUE THREAD

**Issue by coxley** [MarinX/keylogger#4]
When reading from a device, should it go missing the below logic will keep iterating forever while spewing logs. The error is thrown (and logged) in the private `read()` method

https://github.com/MarinX/keylogger/blob/7f76a3573ff8e85adfe6dd82b6c7aadf6761071d/keylogger.go#L63-L66

My suggestion is to add an error return and close the channel so readers can be aware to retry if needed. Only reason I haven't submitted PR for it is it's a change from expectations the library set, where clients must close `events`.

**Comment by MarinX** [comment]
while its not critical bug, I agree about error handling if something happens while reading from file (file removed/blocked etc..)
Thanks for notice, will fix it.

**Comment by MarinX** [comment]
PR merged.
Issue fixed.
Closing issue.
