### ISSUE TITLE
Writing back to the keyboard file possible?

### ISSUE THREAD

**Issue by thornycrackers** [MarinX/keylogger#6]
Hello! Thanks for making this library, it's been a very useful learning reference. I've been using this library as more of "keyboard" library rather than a "keylogger" library and one thing I've been trying to to figure out is how to write a key back to the keyboard file? I've been trying to write with the following code:

```
q_down := InputEvent{
    Type:EvKey,
    Value:1,
    Code:16,
}
q_up := InputEvent{
    Type:EvKey,
    Value:0,
    Code:16
}

keyboard_path := findKeyboardDevice()
fmt.Println(keyboard_path)
time.Sleep(2 * time.Seconds)
fmt.Println("start")

var bin_buf1 bytes.Buffer
binary.Write(&bin_buf1, binary.LittleEndian, q_down)
file.Write(bin_buf1.Bytes())

var bin_buf2 bytes.Buffer
binary.Write(&bin_buf2, binary.LittleEndian, q_up)
file.Write(bin_buf2.Bytes())

fmt.Println("finish")
```

And all I see the text printed but the letter `q` is never printed. I don't know if this code was ever intended for this purpose but I thought you might know the right direction to take with this. Is it possible to implement a `Write` method with it's current implementation?

Thanks for your time!

**Comment by MarinX** [comment]
Hi @thornycrackers ,
Thanks for the feedback!

Did you check the error of file.Write method? 
To satisfy InputEvent struct, try adding the Time and see if that works:
```go
var tv syscall.Timeval
if err := syscall.Gettimeofday(&tv); err != nil {
		panic(err)
}
q_down.Time = tv
```
The `Write` method is a good feature to have. Will try to implement this over the weekend

**Comment by thornycrackers** [comment]
@MarinX Awesome! thank you for the reply!

1. The writes were successful, they were returning nil
2. Adding the Timeval helped buffer the character

Now the only issue that I have is that the character is not typed immediately. When I run the script I expect a `q` to be typed but what happens is that it won't be written until I hit another key (for example lets say `j`). So when I hit the `j` on the keyboard it will actually write `qj` so I think I just need to write some additional bytes after the keyup to signal that it's complete.

**Comment by thornycrackers** [comment]
@MarinX Just a couple updates from some testing I was doing. I was able to get some `c++` code to work properly:

```
#include <stdio.h>
#include <fcntl.h>
#include <linux/input.h>
#include <sstream>
#include <unistd.h>
#include <cstdlib>

#define EV_PRESSED 1
#define EV_RELEASED 0
#define EV_REPEAT 2

void keypress(int key_value) {
    int fd = 0;
    char *device = "/dev/input/event23";

    if( (fd = open(device, O_RDWR)) > 0 ) {
        struct input_event event;
        event.type = EV_KEY;
        event.value = EV_PRESSED;
        event.code = key_value;
        write(fd, &event, sizeof(struct input_event));
        event.value = EV_RELEASED;
        write(fd, &event, sizeof(struct input_event));
        close(fd);
    }
}
```

I then added a c++ header file to my go program so that I could call this code along side what I had already to see what the difference was since the c++ code worked but my go code did not. I wrote an example of the binary data to a file and then used `hexyl` to view both of them.

c++
```
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 48 06 99 25 f9 7f 00 00 ┊ 68 e1 71 00 00 00 00 00 │H•×%×•00┊h×q00000│
│00000010│ 01 00 30 00 01 00 00 00 ┊ 48 06 99 25 f9 7f 00 00 │•000•000┊H•×%×•00│
│00000020│ 68 e1 71 00 00 00 00 00 ┊ 01 00 30 00 00 00 00 00 │h×q00000┊•0000000│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```
golang
```
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 30 3b 37 5d 00 00 00 00 ┊ a5 e7 02 00 00 00 00 00 │0;7]0000┊××•00000│
│00000010│ 01 00 30 00 01 00 00 00 ┊ 30 3b 37 5d 00 00 00 00 │•000•000┊0;7]0000│
│00000020│ da e7 02 00 00 00 00 00 ┊ 01 00 30 00 00 00 00 00 │××•00000┊•0000000│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

I can see that the type, value, and code are working correctly by the positions of the keydown `01 00 30 00 01 00 00 00` and keyup `01 00 30 00 00 00 00 00` in both examples but I don't understand why the binary data for the Timeval is not the same? it also looks as if the go example had 32 bits of precision? Which I'm confused about because (https://golang.org/pkg/syscall/#Timeval) says that it has 64 bits. I'm wondering if it has something to do with `Gettimeofday` but I can't verify that.

**Comment by Rogalek** [comment]
Hey @thornycrackers did you manage to solve this issue and implement working writing? If yes, can I use your fork? Do you have it?

@MarinX are you going to implement this feature? It will be really great and useful here.

**Comment by MarinX** [comment]
Hey @Rogalek  and all. Because of my free time limitation, I will take a closer look over the weekend. Will provide more details...
