### ISSUE TITLE
Proposed feature: add an API that returns all keyboard devices

### ISSUE THREAD

**Issue by spinzed** [MarinX/keylogger#9]
Since there is an API that returns only the first keyboard device path found in `/dev/input/events*/`, it would make sense to make one that returns all that can be detected.
This would be useful for users with multiple (external) keyboards, like myself.
The API would look like this:
```go
func FindAllKeyboardDevices() []string {
    // implementation
}
```
I have implemented this API, I will link the PR when I make it below for review.

**Comment by MarinX** [comment]
PR merged.
Closing issue
